version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: sudo pip install Cython
      - run: sudo python3 setup.py install
      - run: sudo chmod -R 777 /tmp
      - run: sudo python3 -m unittest discover tests


workflows:
  main:
    jobs:
      - build-and-test